#!/usr/bin/env python

import os
import re
import sys


def main():

    caller = os.path.basename(__file__)

    args = []
    kwargs = {}

    shortcut = re.match('^a(ping|traceroute|dig|ssl|ntp|http)$', caller)

    if shortcut:
        verb = "create"
        kwargs["type"] = shortcut.group(1)
    else:
        verb = sys.argv.pop(1)

    try:

        __import__(
            "ripe.atlas.tools.commands." + verb,
            globals(),
            locals(),
            [verb]
        ).Command(*args, **kwargs).run()

    except ImportError as e:
        print("No such command.")

if __name__ == '__main__':
    sys.exit(main())
